# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Conhecimento')),
                ('nivel', models.PositiveIntegerField(default=0, verbose_name='Nivel Conhecimento')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Conhecimentos',
            },
        ),
        migrations.CreateModel(
            name='DadosPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pic_folder/', verbose_name='Imagem Perfil')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome ')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='github')),
                ('linkdin', models.CharField(blank=True, max_length=100, null=True, verbose_name='github')),
                ('ddd', models.CharField(max_length=3, verbose_name='DDD')),
                ('celuar', models.CharField(max_length=9, verbose_name='celeular')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dataNacimento', models.DateField(verbose_name='Data Nascimento')),
                ('conhecimento', models.ManyToManyField(related_name='conhecimento', to='home.Conhecimento', verbose_name='Conhecomento')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'DadosPessoais',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Projeto')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('dataInicio', models.DateField(verbose_name='Data Inicio')),
                ('dataFim', models.DateField(verbose_name='Data Fim')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='dadospessoal',
            name='projetos',
            field=models.ManyToManyField(related_name='projetos', to='home.Projeto', verbose_name='Projetos'),
        ),
    ]
